Server:
  RunMode: debug
  HttpPort: 8040
Database:
  UserName: lixunguang
  Password: "Gotohell@1" #"Gotohell@1" #0925
  Host: 10.30.112.202 #127.0.0.1 :3306 10.30.112.202:3306
  Port: "3306"
  DBName: HSLJ_DB
  Charset: utf8
  ParseTime: True
  Timeout: 10s
  MaxIdleConns: 10
  MaxOpenConns: 20
Redis:
  Host: 127.0.0.1
  Port: 6379
  Password:
  DB: 0
  PoolSize: 3
Logger:
  LogFileDir: log # 日志目录
  ProjectName: JZ_LOG
News:
  NewsNumber: 2 # 首页展示条数，默认为最新的3条
  PictureNewsNumber: 3  # 首页展示图片新闻条数，默认为最新的4条
  PageSize: 3 #默认分页大小
learning:
  ShowNumber: 8 # 首页展示条数，默认为最新的8条
Course:
  CourseNumber: 8 # 首页展示条数，默认为最新的8条
  PageSize: 3 #默认分页大小,目前不使用，前端传入
CDNServer:
  Addr: "http://127.0.0.1:8050/" #"https://7072-prod-8g06gkn605f1c56a-1301228508.tcb.qcloud.la/"   #Addr: Addr: "https://edu2-39379-8-1301228508.sh.run.tcloudbase.com/"
